spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/gestiondestock?createDatabaseIfNotExist=true&userSSL=false&useUnicode=true
    username: root
    password: alioune
    driver-class-name: com.mysql.cj.jdbc.Driver
    
## Specify DBMS
  jpa:
    database: MYSQL
    show-sql: false
    ## Hibernate DDL Auto (create, create-drop, update)
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
          
server:
    port: 8801 
